#!/bin/bash

if [[ ! $WGCTL_INTERFACE ]]; then
	WGCTL_INTERFACE=wg0
fi

usage() {
	echo "usage: $0 <client_name> <client_ip> <quota> <db_file>"
	exit -1
}

if [[ ! $1 ]]; then
	echo "[-] client_name is required"
	usage
fi

if [[ ! $2 ]]; then
	echo "[-] client_ip is required"
	usage
fi

if [[ ! $3 ]]; then
	echo "[-] quota is required"
	usage
fi

if [[ ! $4 ]]; then
	echo "[-] db_file is required"
	usage
fi

name=$1
ip=$2
quota=$3
db_file=$4

if [[ ! -d clients ]]; then
	mkdir clients
fi

if [[ -d clients/$name ]]; then
	echo "[-] client already exists"
	exit -1
fi

echo "[+] creating client dir"
mkdir clients/$name

echo "[+] generating keys"
wg genkey | tee clients/$name/privkey | wg pubkey > clients/$name/pubkey

privkey=$(cat clients/$name/privkey)
pubkey=$(cat clients/$name/pubkey)

echo "[!] name: $name"
echo "[!] ip: $ip"
echo "[!] private key: $privkey"
echo "[!] public key: $pubkey"

echo "[+] adding client $name"
wg set $WGCTL_INTERFACE peer "$pubkey" allowed-ips "$ip/32"

echo "[+] creating client config"
cat > clients/$name/$name.conf <<EOF
[Interface]
# $name
PrivateKey = $privkey
Address = $ip/32
DNS = 1.1.1.1

[Peer]
PublicKey = $(cat server/pubkey)
Endpoint = $(cat server/endpoint)
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF
echo "[!] client config created @ clients/$name/$name.conf"

wg-quick save $WGCTL_INTERFACE

echo "[+] adding quota to db"
sqlite3 $db_file "insert into peers values('$pubkey', '$ip/32', $quota, 0, 0, 0);"

