#!/bin/bash

usage() {
	echo "usage: $0 <ip_prefix> <n> <quota> <db_file> <name_prefix>"
	exit -1
}

if [[ ! $1 ]]; then
	echo "[-] ip_prefix is required"
	usage
fi

if [[ ! $2 ]]; then
	echo "[-] n is required"
	usage
fi

if [[ ! $3 ]]; then
	echo "[-] quota is required"
	usage
fi

if [[ ! $4 ]]; then
	echo "[-] db_file is required"
	usage
fi

if [[ ! $5 ]]; then
	echo "[-] name_prefix is required"
	usage
fi

ip_prefix=$1
n=$2
quota=$3
db_file=$4
name_prefix=$5

if [[ ! -d bulks ]]; then
	mkdir bulks
fi

for ((i=0; i<n; i++))
do
	echo "----------- creating client $i"
	./add-client $name_prefix$i $ip_prefix $quota $db_file
	cp clients/$name_prefix$i/$name_prefix$i.conf bulks
done

