#!/bin/bash

usage() {
  echo "usage: $0 <default-dev> <cidr> <ip> <port>"
  exit -1
}

if [[ $# -lt 4 || $# -gt 4 ]]; then
  usage
fi

dev=$1
cidr=$2
ip=$3
port=$4

if [[ ! -d server ]]; then
  mkdir server
fi

echo "[+] generating keys"
wg genkey | tee server/privkey | wg pubkey > server/pubkey
echo "$ip:$port" > server/endpoint

echo "[+] enabling ip_forward"
sysctl -w net.ipv4.ip_forward=1

echo "[+] generating server config file"
cat > /etc/wireguard/wg0.conf <<EOF
[Interface]
Address = $cidr
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o $dev -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o $dev -j MASQUERADE
ListenPort = $port
PrivateKey = $(cat server/privkey)
EOF

echo "[+] starting wireguard"
systemctl restart wg-quick@wg0
